const $=id=>document.getElementById(id);let FIELDS=[],REG=[];
function fid(id){return 'f_'+id.replaceAll('.','_')}function dmu(id){return 'DMU_'+id.replaceAll('.','_')}function nowDate(){return new Date().toISOString().slice(0,10)}function nowTime(){const d=new Date();return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}function age(v){if(!v)return'';const b=new Date(v+'T00:00:00'),n=new Date();let a=n.getFullYear()-b.getFullYear();const m=n.getMonth()-b.getMonth();if(m<0||(m===0&&n.getDate()<b.getDate()))a--;return a>=0&&a<130?String(a):''}function status(t,k=''){ $('status').textContent=t; $('status').className='status '+k }
async function init(){FIELDS=await fetch('./Data/canonical-fields.json').then(r=>r.json());REG=await fetch('./Data/templates-registry.json').then(r=>r.json());renderForm();renderNativeSelect();renderHistory();status('v1.3 carregado. Escolha um template nativo ou faça upload.','ok')}
function renderForm(){const root=$('formRoot');const groups=[...new Set(FIELDS.map(f=>f.group))];root.innerHTML=groups.map(g=>`<div class="section-title">${g}</div><div class="fields">${FIELDS.filter(f=>f.group===g).map(f=>{let id=fid(f.id), full=f.type==='textarea'?' full':'';let input=f.type==='textarea'?`<textarea id="${id}"></textarea>`:f.type==='select'?`<select id="${id}"><option value=""></option><option>Masculino</option><option>Feminino</option></select>`:`<input id="${id}" type="${f.type==='date'||f.type==='auto_date'?'date':f.type==='auto_time'?'time':'text'}">`;return `<div class="field${full}"><label><span class="code">${f.id}</span>${f.label}</label>${input}</div>`}).join('')}</div>`).join('');$(fid('021')).value=nowDate();$(fid('022')).value=nowTime();$(fid('003')).addEventListener('change',()=>{$(fid('004')).value=age($(fid('003')).value)})}
function renderNativeSelect(){const s=$('nativeTemplate');s.innerHTML=REG.map(t=>`<option value="${t.id}">${t.id} - ${t.name}</option>`).join('')}
function data(){let o={};FIELDS.forEach(f=>{let el=$(fid(f.id));o[f.id]=el?el.value.trim():''});return o}function setData(o){FIELDS.forEach(f=>{let el=$(fid(f.id));if(el)el.value=o[f.id]||''})}
function labelOf(id){return (FIELDS.find(f=>f.id===id)||{}).label||id}function pdfVal(o,id){if(id==='003'||id==='021'){let v=o[id];if(!v)return'';let [y,m,d]=v.split('-');return d&&m&&y?`${d}/${m}/${y}`:v}return o[id]||''}
async function loadPdfBytes(kind){if(kind==='upload'){const f=$('pdfInput').files[0];if(!f)throw new Error('Carregue um PDF externo primeiro.');return await f.arrayBuffer()}const id=$('nativeTemplate').value;const t=REG.find(x=>x.id===id);if(!t)throw new Error('Template nativo não encontrado.');return await fetch(t.file).then(r=>{if(!r.ok)throw new Error('Não consegui carregar o PDF nativo. Verifique se ele está dentro de App/Templates/PDF.');return r.arrayBuffer()})}
async function inspect(kind){try{if(!window.PDFLib){status('PDFLib ainda está carregando. Aguarde.','warn');return}const bytes=await loadPdfBytes(kind);const doc=await PDFLib.PDFDocument.load(bytes);const form=doc.getForm();const fields=form.getFields();if(!fields.length){$('pdfFields').textContent='Nenhum campo AcroForm detectado. Este PDF parece visualmente editável, mas pode estar achatado/sem campos reais.';status('Nenhum campo de formulário detectado.','warn');return}$('pdfFields').textContent=fields.map(f=>`${f.getName()} [${f.constructor?.name||'Field'}]`).join('\n');status(`${fields.length} campo(s) detectado(s).`,'ok')}catch(e){$('pdfFields').textContent='Erro ao inspecionar.';status(e.message||'Erro ao inspecionar PDF.','warn')}}
async function fill(kind){try{if(!window.PDFLib){status('PDFLib ainda está carregando. Aguarde.','warn');return}const bytes=await loadPdfBytes(kind);const doc=await PDFLib.PDFDocument.load(bytes);const form=doc.getForm();const o=data();let filled=0;
for(const f of FIELDS){const names=[dmu(f.id),f.id,f.key,f.label];let field=null;for(const n of names){try{field=form.getTextField(n);break}catch(e){}}if(field){let v=pdfVal(o,f.id);if(v){field.setText(v);filled++}}}
form.updateFieldAppearances();const out=await doc.save();const blob=new Blob([out],{type:'application/pdf'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='delyone-med-unity-documento-preenchido.pdf';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);saveSnapshot(false);status(`PDF gerado. Campos preenchidos: ${filled}.`,'ok')}catch(e){status(e.message||'Erro ao gerar PDF.','warn')}}
function saveSnapshot(show=true){const o=data();const nonempty=Object.values(o).some(Boolean);if(!nonempty){if(show)status('Nada para salvar no histórico.','warn');return}const item={ts:new Date().toISOString(),template:$('nativeTemplate').value,patient:o['001']||'Paciente sem nome',data:o};let h=JSON.parse(localStorage.getItem('dmu_history_v13')||'[]');h.unshift(item);h=h.slice(0,10);localStorage.setItem('dmu_history_v13',JSON.stringify(h));renderHistory();if(show)status('Salvo no histórico local.','ok')}
function renderHistory(){let h=JSON.parse(localStorage.getItem('dmu_history_v13')||'[]');$('historyList').innerHTML=h.length?h.map((it,i)=>`<div class="hist"><b>${it.patient}</b><br>${it.template} · ${new Date(it.ts).toLocaleString()}<br><button class="secondary" onclick="restoreHist(${i})">Restaurar</button></div>`).join(''):'<div class="hist">Sem histórico local ainda.</div>'}window.restoreHist=i=>{let h=JSON.parse(localStorage.getItem('dmu_history_v13')||'[]');if(h[i]){setData(h[i].data);status('Formulário restaurado do histórico local.','ok')}}
$('inspectNative').onclick=()=>inspect('native');$('fillNative').onclick=()=>fill('native');$('inspectUpload').onclick=()=>inspect('upload');$('fillUpload').onclick=()=>fill('upload');$('saveSnapshot').onclick=()=>saveSnapshot(true);$('clearHistory').onclick=()=>{localStorage.removeItem('dmu_history_v13');renderHistory();status('Histórico local apagado.','ok')};$('clearForm').onclick=()=>{if(confirm('Limpar ficha atual?')){FIELDS.forEach(f=>{let el=$(fid(f.id));if(el)el.value=''});$(fid('021')).value=nowDate();$(fid('022')).value=nowTime();status('Ficha limpa.','ok')}};init();